services:
  app:
    image: node:20
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
